version: '3.4'
services:
  web:
    build: docker/site
    ports:
      - 80:80
    volumes:
     - ./www:/var/www/html/
     - ./docker/server/000-default.conf:/etc/apache2/sites-available/000-default.conf
     - ./docker/server/apache2.conf:/etc/apache2/apache2.conf
     - ./docker/server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
     - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: course-php-legacy
      MYSQL_ROOT_PASSWORD: course-legacy
      MYSQL_USER: root
    volumes:
      - ./import.sql:/docker-entrypoint-initdb.d/import.sql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - database
    ports:
      - 8080:80
    environment:
        - PMA_ARBITRARY=1